const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Multiplayer,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Multiplayer.Acts.SyncObject2
	];
};
self.C3_JsPropNameTable = [
	{平铺图: 0},
	{是否可动: 0},
	{栏杆数量: 0},
	{实体: 0},
	{移动到: 0},
	{猫: 0},
	{狗: 0},
	{点1: 0},
	{点2: 0},
	{点3: 0},
	{触控: 0},
	{点4: 0},
	{点5: 0},
	{点6: 0},
	{点7: 0},
	{点8: 0},
	{点9: 0},
	{点10: 0},
	{点11: 0},
	{点12: 0},
	{点13: 0},
	{点14: 0},
	{点15: 0},
	{点16: 0},
	{点17: 0},
	{点18: 0},
	{点19: 0},
	{点20: 0},
	{点21: 0},
	{点22: 0},
	{点23: 0},
	{点24: 0},
	{点25: 0},
	{点26: 0},
	{点27: 0},
	{点28: 0},
	{点29: 0},
	{点30: 0},
	{点31: 0},
	{点32: 0},
	{点33: 0},
	{点34: 0},
	{点35: 0},
	{点36: 0},
	{点37: 0},
	{点38: 0},
	{点39: 0},
	{点40: 0},
	{点41: 0},
	{点42: 0},
	{点43: 0},
	{点44: 0},
	{点45: 0},
	{点46: 0},
	{点47: 0},
	{点48: 0},
	{点49: 0},
	{点50: 0},
	{点51: 0},
	{点52: 0},
	{点53: 0},
	{点54: 0},
	{点55: 0},
	{点56: 0},
	{点57: 0},
	{点58: 0},
	{点59: 0},
	{点60: 0},
	{点61: 0},
	{点62: 0},
	{点63: 0},
	{点64: 0},
	{点65: 0},
	{点66: 0},
	{点67: 0},
	{点68: 0},
	{点69: 0},
	{点70: 0},
	{点71: 0},
	{点72: 0},
	{点73: 0},
	{点74: 0},
	{点75: 0},
	{点76: 0},
	{点77: 0},
	{点78: 0},
	{点79: 0},
	{点80: 0},
	{点81: 0},
	{可否移动: 0},
	{剩余数量: 0},
	{猫棍1: 0},
	{猫棍2: 0},
	{猫棍3: 0},
	{猫棍4: 0},
	{猫棍5: 0},
	{猫棍6: 0},
	{猫棍7: 0},
	{猫棍8: 0},
	{猫棍9: 0},
	{猫棍10: 0},
	{猫横1: 0},
	{猫横2: 0},
	{猫横3: 0},
	{猫横4: 0},
	{猫横5: 0},
	{猫横6: 0},
	{猫横7: 0},
	{猫横8: 0},
	{猫横9: 0},
	{猫横10: 0},
	{是否可移: 0},
	{狗棍1: 0},
	{狗棍2: 0},
	{狗棍3: 0},
	{狗棍4: 0},
	{狗棍5: 0},
	{狗棍6: 0},
	{狗棍7: 0},
	{狗棍8: 0},
	{狗棍9: 0},
	{狗棍10: 0},
	{狗横1: 0},
	{狗横2: 0},
	{狗横3: 0},
	{狗横4: 0},
	{狗横5: 0},
	{狗横6: 0},
	{狗横7: 0},
	{狗横8: 0},
	{狗横9: 0},
	{狗横10: 0},
	{文本: 0},
	{文本2: 0},
	{多人联机: 0},
	{平铺背景2sheet: 0},
	{精灵: 0},
	{点位: 0},
	{拖放: 0},
	{猫横棍: 0},
	{狗横棍: 0}
];

self.InstanceType = {
	平铺图: class extends self.ITiledBackgroundInstance {},
	猫: class extends self.ISpriteInstance {},
	狗: class extends self.ISpriteInstance {},
	点1: class extends self.ISpriteInstance {},
	点2: class extends self.ISpriteInstance {},
	点3: class extends self.ISpriteInstance {},
	触控: class extends self.IInstance {},
	点4: class extends self.ISpriteInstance {},
	点5: class extends self.ISpriteInstance {},
	点6: class extends self.ISpriteInstance {},
	点7: class extends self.ISpriteInstance {},
	点8: class extends self.ISpriteInstance {},
	点9: class extends self.ISpriteInstance {},
	点10: class extends self.ISpriteInstance {},
	点11: class extends self.ISpriteInstance {},
	点12: class extends self.ISpriteInstance {},
	点13: class extends self.ISpriteInstance {},
	点14: class extends self.ISpriteInstance {},
	点15: class extends self.ISpriteInstance {},
	点16: class extends self.ISpriteInstance {},
	点17: class extends self.ISpriteInstance {},
	点18: class extends self.ISpriteInstance {},
	点19: class extends self.ISpriteInstance {},
	点20: class extends self.ISpriteInstance {},
	点21: class extends self.ISpriteInstance {},
	点22: class extends self.ISpriteInstance {},
	点23: class extends self.ISpriteInstance {},
	点24: class extends self.ISpriteInstance {},
	点25: class extends self.ISpriteInstance {},
	点26: class extends self.ISpriteInstance {},
	点27: class extends self.ISpriteInstance {},
	点28: class extends self.ISpriteInstance {},
	点29: class extends self.ISpriteInstance {},
	点30: class extends self.ISpriteInstance {},
	点31: class extends self.ISpriteInstance {},
	点32: class extends self.ISpriteInstance {},
	点33: class extends self.ISpriteInstance {},
	点34: class extends self.ISpriteInstance {},
	点35: class extends self.ISpriteInstance {},
	点36: class extends self.ISpriteInstance {},
	点37: class extends self.ISpriteInstance {},
	点38: class extends self.ISpriteInstance {},
	点39: class extends self.ISpriteInstance {},
	点40: class extends self.ISpriteInstance {},
	点41: class extends self.ISpriteInstance {},
	点42: class extends self.ISpriteInstance {},
	点43: class extends self.ISpriteInstance {},
	点44: class extends self.ISpriteInstance {},
	点45: class extends self.ISpriteInstance {},
	点46: class extends self.ISpriteInstance {},
	点47: class extends self.ISpriteInstance {},
	点48: class extends self.ISpriteInstance {},
	点49: class extends self.ISpriteInstance {},
	点50: class extends self.ISpriteInstance {},
	点51: class extends self.ISpriteInstance {},
	点52: class extends self.ISpriteInstance {},
	点53: class extends self.ISpriteInstance {},
	点54: class extends self.ISpriteInstance {},
	点55: class extends self.ISpriteInstance {},
	点56: class extends self.ISpriteInstance {},
	点57: class extends self.ISpriteInstance {},
	点58: class extends self.ISpriteInstance {},
	点59: class extends self.ISpriteInstance {},
	点60: class extends self.ISpriteInstance {},
	点61: class extends self.ISpriteInstance {},
	点62: class extends self.ISpriteInstance {},
	点63: class extends self.ISpriteInstance {},
	点64: class extends self.ISpriteInstance {},
	点65: class extends self.ISpriteInstance {},
	点66: class extends self.ISpriteInstance {},
	点67: class extends self.ISpriteInstance {},
	点68: class extends self.ISpriteInstance {},
	点69: class extends self.ISpriteInstance {},
	点70: class extends self.ISpriteInstance {},
	点71: class extends self.ISpriteInstance {},
	点72: class extends self.ISpriteInstance {},
	点73: class extends self.ISpriteInstance {},
	点74: class extends self.ISpriteInstance {},
	点75: class extends self.ISpriteInstance {},
	点76: class extends self.ISpriteInstance {},
	点77: class extends self.ISpriteInstance {},
	点78: class extends self.ISpriteInstance {},
	点79: class extends self.ISpriteInstance {},
	点80: class extends self.ISpriteInstance {},
	点81: class extends self.ISpriteInstance {},
	猫棍1: class extends self.ISpriteInstance {},
	猫棍2: class extends self.ISpriteInstance {},
	猫棍3: class extends self.ISpriteInstance {},
	猫棍4: class extends self.ISpriteInstance {},
	猫棍5: class extends self.ISpriteInstance {},
	猫棍6: class extends self.ISpriteInstance {},
	猫棍7: class extends self.ISpriteInstance {},
	猫棍8: class extends self.ISpriteInstance {},
	猫棍9: class extends self.ISpriteInstance {},
	猫棍10: class extends self.ISpriteInstance {},
	猫横1: class extends self.ISpriteInstance {},
	猫横2: class extends self.ISpriteInstance {},
	猫横3: class extends self.ISpriteInstance {},
	猫横4: class extends self.ISpriteInstance {},
	猫横5: class extends self.ISpriteInstance {},
	猫横6: class extends self.ISpriteInstance {},
	猫横7: class extends self.ISpriteInstance {},
	猫横8: class extends self.ISpriteInstance {},
	猫横9: class extends self.ISpriteInstance {},
	猫横10: class extends self.ISpriteInstance {},
	狗棍1: class extends self.ISpriteInstance {},
	狗棍2: class extends self.ISpriteInstance {},
	狗棍3: class extends self.ISpriteInstance {},
	狗棍4: class extends self.ISpriteInstance {},
	狗棍5: class extends self.ISpriteInstance {},
	狗棍6: class extends self.ISpriteInstance {},
	狗棍7: class extends self.ISpriteInstance {},
	狗棍8: class extends self.ISpriteInstance {},
	狗棍9: class extends self.ISpriteInstance {},
	狗棍10: class extends self.ISpriteInstance {},
	狗横1: class extends self.ISpriteInstance {},
	狗横2: class extends self.ISpriteInstance {},
	狗横3: class extends self.ISpriteInstance {},
	狗横4: class extends self.ISpriteInstance {},
	狗横5: class extends self.ISpriteInstance {},
	狗横6: class extends self.ISpriteInstance {},
	狗横7: class extends self.ISpriteInstance {},
	狗横8: class extends self.ISpriteInstance {},
	狗横9: class extends self.ISpriteInstance {},
	狗横10: class extends self.ISpriteInstance {},
	文本: class extends self.ITextInstance {},
	文本2: class extends self.ITextInstance {},
	多人联机: class extends self.IInstance {},
	平铺背景2sheet: class extends self.ISpriteInstance {},
	精灵: class extends self.ISpriteInstance {},
	点位: class extends self.ISpriteInstance {},
	猫横棍: class extends self.ISpriteInstance {},
	狗横棍: class extends self.ISpriteInstance {}
}